- name: myPlaybook
  hosts: hosts
  vars:
    project_path: /var/www/nodejs

  tasks:
    - name: Set some variable
      set_fact:
          release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
          current_path: "{{ project_path }}/current"

    - name: Create new folder
      file:
              dest={{ release_path }}
              mode=0755
              recurse=yes
              state=directory

    - name: Clone the repository
      git:
              repo: https://github.com/pechpaul/streamhost.git
              dest: "{{ release_path }}"

    - name: install npm
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
      - npm

    - name: Update npm
      npm:
              path={{ release_path }}

    - name: Update symlink
      file:
              src={{ release_path }}
              dest={{ current_path }}
              state=link

    - name: Delete old pm2 process
      command: pm2 delete ws-node
      ignore_errors: yes

    - name: Delete old dir
      shell: rm -rf {{ current_release_path.stdout }}/
      when: current_release_path.stdout != current_path

    - name: run server
      command: node {{ release_path }}/index.js